name: Build and Publish to Google Artifact Registry

on:
  push:
    branches:
      - main

env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  GOOGLE_CLOUD_PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
  GCR_NAME: ${{ secrets.GCR_NAME }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  GAR_REPOSITORY: ${{ secrets.GAR_REPOSITORY }}

jobs:
  setup-and0build:
    name: Setup and Build
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker
    
      - name: Build Docker Image for Container Registry
        run: |-
          docker build -t eu.gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/${{ secrets.GCR_NAME }}:$GITHUB_SHA . 

      - name: Push Docker Image to Google Container Registry
        run: |-
          docker push eu.gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/${{ secrets.GCR_NAME }}:$GITHUB_SHA

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    #   - name: Build for Artifact Registry
    #     run: |-
    #         docker build --tag "${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/${{ secrets.GAR_REPOSITORY }}/${{ secrets.GCR_NAME }}:$GITHUB_SHA" .

    #   - name: Publish to Google Artifact Registry
    #     run: |-
    #       docker push "${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/${{ secrets.GAR_REPOSITORY }}/${{ secrets.GCR_NAME }}:$GITHUB_SHA"
    
    # Set up kustomize
    # - name: Set up Kustomize
    #   run: |-
    #     curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
    #     chmod u+x ./kustomize

    # Deploy the Docker image to the GKE cluster
    # - name: Deploy
    #   run: |-
    #     ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
    #     ./kustomize build . | kubectl apply -f -
    #     kubectl rollout status deployment/$DEPLOYMENT_NAME
    #     kubectl get services -o wide